development: &default
  host: "http://es-container:9200/"
  transport_options:
    request:
      timeout: !!integer 300
test:
  <<: *default
staging:
  <<: *default
production:
  host: "http://es-container:9200/"
  transport_options:
    request:
      timeout: !!integer 300